### ISSUE TITLE
Great Project

### ISSUE THREAD

**Issue by jbaron** [ECharts-Java/ECharts-Java#60]
Not an issue, but a big "Thank You" for releasing this great project.

I migrated almost all my chart to using the ECharts-Java framework and it works like a charm. 

To see the results, use the below link to open a notebook on mybinder.org (might take some time to build it) and then from the Jupyter menu select "Run -> Run All Cells"

https://mybinder.org/v2/gh/neurallayer/roboquant-notebook/main?urlpath=lab/tree/tutorials/charts.ipynb

All the charts you'll see (except the first one) are now using the ECharts-Java library.

**Comment by incandescentxxc** [comment]
That is awesome! This project starts as a baby of a course project and we are so glad that it has grown to help you migrate almost all your charts. This is definitely something new and special to us because it is making a real contribution to the open source community!

Would you mind if we feature Neural Layer for the usage of ECharts-Java in our ReadMe or LinkedIn for some promotion purpose?

And feel free to raise any other issues during your use of ECharts-Java in the future:)

**Comment by jbaron** [comment]
Feel free to refer to Neural Layer in the readme and LinkedIn,  it is my honour. If you like you can also refer to roboquant (roboquant.org) as the application that uses it.
